import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { ToastProvider } from '@/components/ui/toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      afterSignInUrl="/"
      afterSignUpUrl="/"
      appearance={{

        elements: {
          
              button: "!bg-[var(--color-elevated)] !text-[var(--color-text)] !fill-black",

              cardBox: "!border-none !border-transparent !shadow-none !shadow-transparent",

              card: "!border-none !border-transparent !shadow-none !shadow-transparent",

              formButtonPrimary: "!bg-neutral-900 !text-white",

              // formField__username: "!bg-[var(--color-elevated)]",




              
            },
        // theme: 'simple',
        // baseTheme: shadcn,
        // baseTheme: 'simple', 
        variables: {
          // use the CSS variable that backs `bg-surface` so Clerk follows light/dark modes
          colorBackground: 'var(--color-surface)',
        },
      }}
    >
      <html lang="en">
        <body className={`antialiased`}>
          <ToastProvider>
            {children}
          </ToastProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
